//go:build ignore

package v4l

// +godefs map struct_timeval Timeval

/*
#include <linux/videodev2.h>
*/
import "C"
import "syscall"

const (
	PIX_FMT_YUV420 = C.V4L2_PIX_FMT_YUV420
	PIX_FMT_NV12   = C.V4L2_PIX_FMT_NV12
	PIX_FMT_NV21   = C.V4L2_PIX_FMT_NV21
	PIX_FMT_H264   = C.V4L2_PIX_FMT_H264
	PIX_FMT_JPEG   = C.V4L2_PIX_FMT_JPEG
	PIX_FMT_MJPEG  = C.V4L2_PIX_FMT_MJPEG
	PIX_FMT_RGB24  = C.V4L2_PIX_FMT_RGB24
	PIX_FMT_BGR24  = C.V4L2_PIX_FMT_BGR24
	PIX_FMT_YUYV   = C.V4L2_PIX_FMT_YUYV
	PIX_FMT_YVYU   = C.V4L2_PIX_FMT_YVYU
	PIX_FMT_VYUY   = C.V4L2_PIX_FMT_VYUY
	PIX_FMT_UYVY   = C.V4L2_PIX_FMT_UYVY
)

const (
	FRMSIZE_TYPE_DISCRETE   = C.V4L2_FRMSIZE_TYPE_DISCRETE
	FRMSIZE_TYPE_CONTINUOUS = C.V4L2_FRMSIZE_TYPE_CONTINUOUS
	FRMSIZE_TYPE_STEPWISE   = C.V4L2_FRMSIZE_TYPE_STEPWISE
)

const (
	FRMIVAL_TYPE_DISCRETE   = C.V4L2_FRMIVAL_TYPE_DISCRETE
	FRMIVAL_TYPE_CONTINUOUS = C.V4L2_FRMIVAL_TYPE_CONTINUOUS
	FRMIVAL_TYPE_STEPWISE   = C.V4L2_FRMIVAL_TYPE_STEPWISE
)

const (
	CAP_VIDEO_CAPTURE        = C.V4L2_CAP_VIDEO_CAPTURE
	CAP_VIDEO_CAPTURE_MPLANE = C.V4L2_CAP_VIDEO_CAPTURE_MPLANE
	CAP_VIDEO_OUTPUT         = C.V4L2_CAP_VIDEO_OUTPUT
	CAP_VIDEO_OUTPUT_MPLANE  = C.V4L2_CAP_VIDEO_OUTPUT_MPLANE
	CAP_VIDEO_M2M            = C.V4L2_CAP_VIDEO_M2M
	CAP_VIDEO_M2M_MPLANE     = C.V4L2_CAP_VIDEO_M2M_MPLANE
	CAP_STREAMING            = C.V4L2_CAP_STREAMING
	CAP_DEVICE_CAPS          = C.V4L2_CAP_DEVICE_CAPS
	CAP_EXT_PIX_FORMAT       = C.V4L2_CAP_EXT_PIX_FORMAT
)

const (
	CID_VFLIP  = C.V4L2_CID_VFLIP
	CID_HFLIP  = C.V4L2_CID_HFLIP
	CID_ROTATE = C.V4L2_CID_ROTATE

	CID_MPEG_VIDEO_REPEAT_SEQ_HEADER = C.V4L2_CID_MPEG_VIDEO_REPEAT_SEQ_HEADER
	CID_MPEG_VIDEO_H264_I_PERIOD     = C.V4L2_CID_MPEG_VIDEO_H264_I_PERIOD
	CID_MPEG_VIDEO_H264_PROFILE      = C.V4L2_CID_MPEG_VIDEO_H264_PROFILE
	CID_MPEG_VIDEO_BITRATE_MODE      = C.V4L2_CID_MPEG_VIDEO_BITRATE_MODE
	CID_MPEG_VIDEO_BITRATE           = C.V4L2_CID_MPEG_VIDEO_BITRATE

	CID_SCENE_MODE = C.V4L2_CID_SCENE_MODE

	CID_EXPOSURE_AUTO          = C.V4L2_CID_EXPOSURE_AUTO
	CID_EXPOSURE_ABSOLUTE      = C.V4L2_CID_EXPOSURE_ABSOLUTE
	CID_AUTO_EXPOSURE_BIAS     = C.V4L2_CID_AUTO_EXPOSURE_BIAS
	CID_EXPOSURE_AUTO_PRIORITY = C.V4L2_CID_EXPOSURE_AUTO_PRIORITY
)

const (
	MPEG_VIDEO_H264_PROFILE_BASELINE             = C.V4L2_MPEG_VIDEO_H264_PROFILE_BASELINE
	MPEG_VIDEO_H264_PROFILE_CONSTRAINED_BASELINE = C.V4L2_MPEG_VIDEO_H264_PROFILE_CONSTRAINED_BASELINE
	MPEG_VIDEO_H264_PROFILE_MAIN                 = C.V4L2_MPEG_VIDEO_H264_PROFILE_MAIN
	MPEG_VIDEO_H264_PROFILE_EXTENDED             = C.V4L2_MPEG_VIDEO_H264_PROFILE_EXTENDED
	MPEG_VIDEO_H264_PROFILE_HIGH                 = C.V4L2_MPEG_VIDEO_H264_PROFILE_HIGH
)

const (
	SCENE_MODE_NONE   = C.V4L2_SCENE_MODE_NONE
	SCENE_MODE_SPORTS = C.V4L2_SCENE_MODE_SPORTS
)

const (
	EXPOSURE_AUTO              = C.V4L2_EXPOSURE_AUTO
	EXPOSURE_MANUAL            = C.V4L2_EXPOSURE_MANUAL
	EXPOSURE_SHUTTER_PRIORITY  = C.V4L2_EXPOSURE_SHUTTER_PRIORITY
	EXPOSURE_APERTURE_PRIORITY = C.V4L2_EXPOSURE_APERTURE_PRIORITY
)

const (
	BUF_FLAG_TIMESTAMP_COPY      = C.V4L2_BUF_FLAG_TIMESTAMP_COPY
	BUF_FLAG_TIMESTAMP_MONOTONIC = C.V4L2_BUF_FLAG_TIMESTAMP_MONOTONIC
)

const (
	BUF_TYPE_VIDEO_CAPTURE        = C.V4L2_BUF_TYPE_VIDEO_CAPTURE
	BUF_TYPE_VIDEO_CAPTURE_MPLANE = C.V4L2_BUF_TYPE_VIDEO_CAPTURE_MPLANE
	BUF_TYPE_VIDEO_OUTPUT_MPLANE  = C.V4L2_BUF_TYPE_VIDEO_OUTPUT_MPLANE
)

const (
	MEMORY_MMAP = C.V4L2_MEMORY_MMAP
)

const (
	VIDIOC_DQBUF               = C.VIDIOC_DQBUF
	VIDIOC_G_CTRL              = C.VIDIOC_G_CTRL
	VIDIOC_G_FMT               = C.VIDIOC_G_FMT
	VIDIOC_G_PARM              = C.VIDIOC_G_PARM
	VIDIOC_QBUF                = C.VIDIOC_QBUF
	VIDIOC_QUERYBUF            = C.VIDIOC_QUERYBUF
	VIDIOC_QUERYCAP            = C.VIDIOC_QUERYCAP
	VIDIOC_QUERYCTRL           = C.VIDIOC_QUERYCTRL
	VIDIOC_REQBUFS             = C.VIDIOC_REQBUFS
	VIDIOC_S_CTRL              = C.VIDIOC_S_CTRL
	VIDIOC_S_FMT               = C.VIDIOC_S_FMT
	VIDIOC_S_PARM              = C.VIDIOC_S_PARM
	VIDIOC_STREAMOFF           = C.VIDIOC_STREAMOFF
	VIDIOC_STREAMON            = C.VIDIOC_STREAMON
	VIDIOC_ENUM_FMT            = C.VIDIOC_ENUM_FMT
	VIDIOC_ENUM_FRAMESIZES     = C.VIDIOC_ENUM_FRAMESIZES
	VIDIOC_ENUM_FRAMEINTERVALS = C.VIDIOC_ENUM_FRAMEINTERVALS
)

type Timeval = syscall.Timeval

type Buffer C.struct_v4l2_buffer

type Capability C.struct_v4l2_capability

type Captureparm C.struct_v4l2_captureparm

type Control C.struct_v4l2_control

type Fmtdesc C.struct_v4l2_fmtdesc

type Frmsizeenum C.struct_v4l2_frmsizeenum

type FrmsizeStepwise C.struct_v4l2_frmsize_stepwise

type FrmsizeDiscrete C.struct_v4l2_frmsize_discrete

type Frmivalenum C.struct_v4l2_frmivalenum

type FrmivalStepwise C.struct_v4l2_frmival_stepwise

type Format C.struct_v4l2_format

type Fract C.struct_v4l2_fract

type Outputparm C.struct_v4l2_outputparm

type PixFormat C.struct_v4l2_pix_format

type PixFormatMplane C.struct_v4l2_pix_format_mplane

type Plane C.struct_v4l2_plane

type PlanePixFormat C.struct_v4l2_plane_pix_format

type Requestbuffers C.struct_v4l2_requestbuffers

type Streamparm C.struct_v4l2_streamparm

type Timecode C.struct_v4l2_timecode
