// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types.go

package v4l

import "syscall"

const (
	PIX_FMT_YUV420 = 0x32315559
	PIX_FMT_NV12   = 0x3231564e
	PIX_FMT_NV21   = 0x3132564e
	PIX_FMT_H264   = 0x34363248
	PIX_FMT_JPEG   = 0x4745504a
	PIX_FMT_MJPEG  = 0x47504a4d
	PIX_FMT_RGB24  = 0x33424752
	PIX_FMT_BGR24  = 0x33524742
	PIX_FMT_YUYV   = 0x56595559
	PIX_FMT_YVYU   = 0x55595659
	PIX_FMT_VYUY   = 0x59555956
	PIX_FMT_UYVY   = 0x59565955
)

const (
	FRMSIZE_TYPE_DISCRETE   = 0x1
	FRMSIZE_TYPE_CONTINUOUS = 0x2
	FRMSIZE_TYPE_STEPWISE   = 0x3
)

const (
	FRMIVAL_TYPE_DISCRETE   = 0x1
	FRMIVAL_TYPE_CONTINUOUS = 0x2
	FRMIVAL_TYPE_STEPWISE   = 0x3
)

const (
	CAP_VIDEO_CAPTURE        = 0x1
	CAP_VIDEO_CAPTURE_MPLANE = 0x1000
	CAP_VIDEO_OUTPUT         = 0x2
	CAP_VIDEO_OUTPUT_MPLANE  = 0x2000
	CAP_VIDEO_M2M            = 0x8000
	CAP_VIDEO_M2M_MPLANE     = 0x4000
	CAP_STREAMING            = 0x4000000
	CAP_DEVICE_CAPS          = 0x80000000
	CAP_EXT_PIX_FORMAT       = 0x200000
)

const (
	CID_VFLIP  = 0x980915
	CID_HFLIP  = 0x980914
	CID_ROTATE = 0x980922

	CID_MPEG_VIDEO_REPEAT_SEQ_HEADER = 0x9909e2
	CID_MPEG_VIDEO_H264_I_PERIOD     = 0x990a66
	CID_MPEG_VIDEO_H264_PROFILE      = 0x990a6b
	CID_MPEG_VIDEO_BITRATE_MODE      = 0x9909ce
	CID_MPEG_VIDEO_BITRATE           = 0x9909cf

	CID_SCENE_MODE = 0x9a091a

	CID_EXPOSURE_AUTO          = 0x9a0901
	CID_EXPOSURE_ABSOLUTE      = 0x9a0902
	CID_AUTO_EXPOSURE_BIAS     = 0x9a0913
	CID_EXPOSURE_AUTO_PRIORITY = 0x9a0903
)

const (
	MPEG_VIDEO_H264_PROFILE_BASELINE             = 0x0
	MPEG_VIDEO_H264_PROFILE_CONSTRAINED_BASELINE = 0x1
	MPEG_VIDEO_H264_PROFILE_MAIN                 = 0x2
	MPEG_VIDEO_H264_PROFILE_EXTENDED             = 0x3
	MPEG_VIDEO_H264_PROFILE_HIGH                 = 0x4
)

const (
	SCENE_MODE_NONE   = 0x0
	SCENE_MODE_SPORTS = 0xb
)

const (
	EXPOSURE_AUTO              = 0x0
	EXPOSURE_MANUAL            = 0x1
	EXPOSURE_SHUTTER_PRIORITY  = 0x2
	EXPOSURE_APERTURE_PRIORITY = 0x3
)

const (
	BUF_FLAG_TIMESTAMP_COPY      = 0x4000
	BUF_FLAG_TIMESTAMP_MONOTONIC = 0x2000
)

const (
	BUF_TYPE_VIDEO_CAPTURE        = 0x1
	BUF_TYPE_VIDEO_CAPTURE_MPLANE = 0x9
	BUF_TYPE_VIDEO_OUTPUT_MPLANE  = 0xa
)

const (
	MEMORY_MMAP = 0x1
)

const (
	VIDIOC_DQBUF               = 0xc0585611
	VIDIOC_G_CTRL              = 0xc008561b
	VIDIOC_G_FMT               = 0xc0d05604
	VIDIOC_G_PARM              = 0xc0cc5615
	VIDIOC_QBUF                = 0xc058560f
	VIDIOC_QUERYBUF            = 0xc0585609
	VIDIOC_QUERYCAP            = 0x80685600
	VIDIOC_QUERYCTRL           = 0xc0445624
	VIDIOC_REQBUFS             = 0xc0145608
	VIDIOC_S_CTRL              = 0xc008561c
	VIDIOC_S_FMT               = 0xc0d05605
	VIDIOC_S_PARM              = 0xc0cc5616
	VIDIOC_STREAMOFF           = 0x40045613
	VIDIOC_STREAMON            = 0x40045612
	VIDIOC_ENUM_FMT            = 0xc0405602
	VIDIOC_ENUM_FRAMESIZES     = 0xc02c564a
	VIDIOC_ENUM_FRAMEINTERVALS = 0xc034564b
)

type Timeval = syscall.Timeval

type Buffer struct {
	Index     uint32
	Type      uint32
	Bytesused uint32
	Flags     uint32
	Field     uint32
	Timestamp Timeval
	Timecode  Timecode
	Sequence  uint32
	Memory    uint32
	M         [8]byte
	Length    uint32
	Reserved2 uint32
	Fd        int32
	Pad_cgo_0 [4]byte
}

type Capability struct {
	Driver       [16]uint8
	Card         [32]uint8
	Bus_info     [32]uint8
	Version      uint32
	Capabilities uint32
	Device_caps  uint32
	Reserved     [3]uint32
}

type Captureparm struct {
	Capability   uint32
	Capturemode  uint32
	Timeperframe Fract
	Extendedmode uint32
	Readbuffers  uint32
	Reserved     [4]uint32
}

type Control struct {
	Id    uint32
	Value int32
}

type Fmtdesc struct {
	Index       uint32
	Type        uint32
	Flags       uint32
	Description [32]uint8
	Pixelformat uint32
	Code        uint32
	Reserved    [3]uint32
}

type Frmsizeenum struct {
	Index     uint32
	Format    uint32
	Type      uint32
	Discrete  FrmsizeDiscrete
	Pad_cgo_0 [16]byte
	Reserved  [2]uint32
}

type FrmsizeStepwise struct {
	Min_width   uint32
	Max_width   uint32
	Step_width  uint32
	Min_height  uint32
	Max_height  uint32
	Step_height uint32
}

type FrmsizeDiscrete struct {
	Width  uint32
	Height uint32
}

type Frmivalenum struct {
	Index     uint32
	Format    uint32
	Width     uint32
	Height    uint32
	Type      uint32
	Discrete  Fract
	Pad_cgo_0 [16]byte
	Reserved  [2]uint32
}

type FrmivalStepwise struct {
	Min  Fract
	Max  Fract
	Step Fract
}

type Format struct {
	Type      uint32
	Pad_cgo_0 [4]byte
	Fmt       [200]byte
}

type Fract struct {
	Numerator   uint32
	Denominator uint32
}

type Outputparm struct {
	Capability   uint32
	Outputmode   uint32
	Timeperframe Fract
	Extendedmode uint32
	Writebuffers uint32
	Reserved     [4]uint32
}

type PixFormat struct {
	Width        uint32
	Height       uint32
	Pixelformat  uint32
	Field        uint32
	Bytesperline uint32
	Sizeimage    uint32
	Colorspace   uint32
	Priv         uint32
	Flags        uint32
	Ycbcr_enc    uint32
	Quantization uint32
	Xfer_func    uint32
}

type PixFormatMplane struct {
	Width        uint32
	Height       uint32
	Pixelformat  uint32
	Field        uint32
	Colorspace   uint32
	Plane_fmt    [8]PlanePixFormat
	Num_planes   uint8
	Flags        uint8
	Ycbcr_enc    uint8
	Quantization uint8
	Xfer_func    uint8
	Reserved     [7]uint8
}

type Plane struct {
	Bytesused uint32
	Length    uint32
	M         [8]byte
	Offset    uint32
	Reserved  [11]uint32
}

type PlanePixFormat struct {
	Sizeimage    uint32
	Bytesperline uint32
	Reserved     [6]uint16
}

type Requestbuffers struct {
	Count        uint32
	Type         uint32
	Memory       uint32
	Capabilities uint32
	Flags        uint8
	Reserved     [3]uint8
}

type Streamparm struct {
	Type uint32
	Parm [200]byte
}

type Timecode struct {
	Type     uint32
	Flags    uint32
	Frames   uint8
	Seconds  uint8
	Minutes  uint8
	Hours    uint8
	Userbits [4]uint8
}
